name: Bug
description: Algo no funciona en el juego
title: "[Bug] "
labels: ["bug", "equipo:desarrollo"]
body:
  - type: textarea
    id: que
    attributes: { label: ¿Qué pasó?, description: "Y qué esperabas que pasara" }
    validations: { required: true }
  - type: textarea
    id: pasos
    attributes: { label: Pasos para reproducirlo }
  - type: input
    id: visor
    attributes: { label: Visor / build, placeholder: "Quest 2, build del 15/oct" }
